name: CI
on: [workflow_dispatch, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        enumerator: [1, 2, 3]

    steps:
      - name: Run a one-line script
        run: echo Hello, world!
  
  release:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
        
  publish-cm-record:
    needs: release
    runs-on: ubuntu-latest
    
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
